"""add church invite_code

Revision ID: 01535668f7c3
Revises: 8bba19ef0b4d
Create Date: 2026-01-07 14:41:05.270403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01535668f7c3'
down_revision: Union[str, Sequence[str], None] = '8bba19ef0b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('churches', sa.Column('invite_code', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'churches', ['invite_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'churches', type_='unique')
    op.drop_column('churches', 'invite_code')
    # ### end Alembic commands ###
