"""add status column

Revision ID: 36f8dfa1235b
Revises: e87eca56c923
Create Date: 2026-01-07 16:44:45.364136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f8dfa1235b'
down_revision: Union[str, Sequence[str], None] = 'e87eca56c923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1) ajouter la colonne en nullable pour ne pas casser les anciennes lignes
    op.add_column("users", sa.Column("status", sa.String(length=20), nullable=True))

    # 2) donner une valeur aux users existants
    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL")

    # 3) rendre la colonne obligatoire
    op.alter_column("users", "status", nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
