"""create themes songs theme_songs

Revision ID: 3ba94a8e9fd2
Revises: d481ab8e5951
Create Date: 2026-01-19 09:59:47.884541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba94a8e9fd2'
down_revision: Union[str, Sequence[str], None] = 'd481ab8e5951'
# down_revision: Union[str, Sequence[str], None] = '36f8dfa1235b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
